spring.application.name=myproject
server.port=8080

# MySQL Workbench Connection to leaguetrack_db
spring.datasource.url=jdbc:mysql://localhost:3306/leaguetrack_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate / JPA Configuration
# Automatically creates and updates all 4 tables inside leaguetrack_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Springdoc OpenAPI / Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operations-sorter=method